/** S3 Heat Ch.1 — Thermometer, internal energy, change of state & heat transfer */
export const QUIZ_SECTIONS = [
  { id: "thermometer", label: "Thermometer", labelZh: "溫度計" },
  { id: "heat-internal-energy", label: "Heat and internal energy", labelZh: "熱與內能" },
  { id: "change-of-state", label: "Change of state", labelZh: "物態變化" },
  { id: "heat-transfer", label: "Heat transfer", labelZh: "熱傳遞" },
];

export const QUIZ_ITEMS = [
  {
    id: "therm-q01",
    section: "thermometer",
    difficulty: "Foundation",
    stem: "Which of the following thermometers measures temperature by detecting the intensity of radiation?",
    options: [
      { key: "A", text: "Liquid-in-glass thermometer" },
      { key: "B", text: "Resistance thermometer" },
      { key: "C", text: "Thermistor thermometer" },
      { key: "D", text: "Infra-red thermometer" },
    ],
    answer: "D",
    hint: "The intensity of infra-red radiation given out by an object increases when its temperature increases.",
  },
  {
    id: "therm-q02",
    section: "thermometer",
    difficulty: "Standard",
    stem: "A thermometer makes use of the resistance R of a material to measure temperature. The figure below shows how R varies with temperature T.\n\nWhat is the temperature when R is 100 Ω?",
    options: [
      { key: "A", text: "25 °C" },
      { key: "B", text: "45 °C" },
      { key: "C", text: "55 °C" },
      { key: "D", text: "105 °C" },
    ],
    answer: "C",
    hint: "Use linear interpolation on the R–T graph between the marked points.",
    image: {
      src: "./assets/therm-q02-rt-graph.png",
      alt: "Graph of resistance R against temperature T",
      caption: "Fig · R–T graph",
    },
  },
  {
    id: "therm-q03",
    section: "thermometer",
    difficulty: "Foundation",
    stem: "The graph below shows the variation of a property P of two materials X and Y with temperature T.\n\nWhich of the following statements is correct?",
    options: [
      { key: "A", text: "Only X is suitable for making thermometers." },
      { key: "B", text: "Only Y is suitable for making thermometers." },
      { key: "C", text: "Both X and Y are suitable for making thermometers." },
      { key: "D", text: "Neither X nor Y is suitable for making thermometers." },
    ],
    answer: "C",
    hint: "Each value of P must correspond to a single temperature T for thermometer use.",
  },
  {
    id: "therm-q04",
    section: "thermometer",
    difficulty: "Foundation",
    stem: "Which of the following methods can improve the sensitivity of a liquid-in-glass thermometer?\n(1) Reduce the diameter of the glass tube.\n(2) Increase the length of the glass tube.\n(3) Use a liquid which expands less for the same temperature increase.",
    options: [
      { key: "A", text: "(1) only" },
      { key: "B", text: "(2) only" },
      { key: "C", text: "(1) and (3) only" },
      { key: "D", text: "(2) and (3) only" },
    ],
    answer: "A",
    hint: "A narrower tube gives a larger column rise for the same volume expansion.",
  },
  {
    id: "therm-q05",
    section: "thermometer",
    difficulty: "Foundation",
    stem: "Which of the following statements about the Celsius temperature scale is/are correct?\n(1) The lower fixed point is the lowest temperature existing in nature.\n(2) The upper fixed point is the temperature of steam.\n(3) The unit of this scale is °C.",
    options: [
      { key: "A", text: "(1) only" },
      { key: "B", text: "(3) only" },
      { key: "C", text: "(1) and (2) only" },
      { key: "D", text: "(2) and (3) only" },
    ],
    answer: "B",
    hint: "The lower fixed point is 0 °C; the upper fixed point is the boiling point of pure water at 1 atm.",
  },
  {
    id: "therm-q06",
    section: "thermometer",
    difficulty: "Standard",
    stem: "Mary calibrates a liquid-in-glass thermometer by putting it in water at room temperature of 25 °C and pure boiling water in turn. The length of the liquid column increases by 16 cm in the process. Then she puts the thermometer in a glass of water of unknown temperature T. The liquid column is 8 cm above the level corresponding to 25 °C. Find T.",
    options: [
      { key: "A", text: "25.2 °C" },
      { key: "B", text: "37.5 °C" },
      { key: "C", text: "50.0 °C" },
      { key: "D", text: "62.5 °C" },
    ],
    answer: "D",
    hint: "8 cm is half of the 16 cm rise from 25 °C to 100 °C.",
  },
  {
    id: "therm-q07",
    section: "thermometer",
    difficulty: "Foundation",
    stem: "Which of the following statements about thermometer is incorrect?",
    options: [
      { key: "A", text: "All thermometers are using the Celsius temperature scale." },
      { key: "B", text: "Thermometer is an instrument for measuring the degree of hotness of an object." },
      { key: "C", text: "All types of thermometers make use of the temperature-dependent properties of materials." },
      { key: "D", text: "The temperature of steam point measured by different types of thermometers should be the same." },
    ],
    answer: "A",
    hint: "Fahrenheit and Kelvin scales are also used in thermometers.",
  },
  {
    id: "therm-q08",
    section: "thermometer",
    difficulty: "Foundation",
    stem: "Which of the following temperatures is different from the others?",
    options: [
      { key: "A", text: "0 °C" },
      { key: "B", text: "Upper fixed point of the Celsius temperature scale" },
      { key: "C", text: "Ice point" },
      { key: "D", text: "Temperature of melting ice" },
    ],
    answer: "B",
    hint: "The upper fixed point is 100 °C; the others are 0 °C.",
  },
  {
    id: "therm-q09",
    section: "thermometer",
    difficulty: "Standard",
    stem: "A faulty thermometer with uniform scale reads 5 °C and 95 °C when it is placed in melting ice and boiling water respectively. What is the actual temperature if the thermometer reads 30 °C?",
    options: [
      { key: "A", text: "27.8 °C" },
      { key: "B", text: "28.5 °C" },
      { key: "C", text: "30 °C" },
      { key: "D", text: "35 °C" },
    ],
    answer: "A",
    hint: "Use proportional intervals: T/100 = (30 − 5)/(95 − 5).",
  },
  {
    id: "therm-q10",
    section: "thermometer",
    difficulty: "Foundation",
    stem: "The graphs below show the variation of the electrical resistance R of four circuit elements with temperature. Which of the circuit elements is the most suitable for measuring temperature?",
    options: [
      { key: "A", text: "Graph A" },
      { key: "B", text: "Graph B" },
      { key: "C", text: "Graph C" },
      { key: "D", text: "Graph D" },
    ],
    answer: "C",
    hint: "A resistance thermometer needs R to vary linearly with temperature over the working range.",
    image: {
      src: "./assets/therm-q10-resistance-graphs.png",
      alt: "Four graphs A–D showing resistance R against temperature T",
      caption: "Fig · R–T graphs for four circuit elements",
    },
  },
  {
    id: "heat-q01",
    section: "heat-internal-energy",
    difficulty: "Foundation",
    stem: "Which of the following pairs of objects have the same specific heat capacity?\n(1) 1 kg of oil and 3 kg of oil\n(2) A 1-kg cubic copper block and a 1-kg long copper wire\n(3) 1 kg of solid wax and 1 kg of liquid wax",
    options: [
      { key: "A", text: "(1) and (2) only" },
      { key: "B", text: "(1) and (3) only" },
      { key: "C", text: "(2) and (3) only" },
      { key: "D", text: "(1), (2) and (3)" },
    ],
    answer: "A",
    hint: "Specific heat capacity depends on the substance and state, not mass or shape.",
  },
  {
    id: "heat-q02",
    section: "heat-internal-energy",
    difficulty: "Applied",
    stem: "A heater supplies energy at 800 W to a cup of water for 100 s. The mass of the water is 350 g and its initial temperature is 25 °C. Assume the cup has negligible heat capacity and there is no energy lost to the surroundings. Find the final temperature of the water.\n(Specific heat capacity of water = 4200 J kg⁻¹ °C⁻¹)",
    options: [
      { key: "A", text: "32 °C" },
      { key: "B", text: "54 °C" },
      { key: "C", text: "79 °C" },
      { key: "D", text: "100 °C" },
    ],
    answer: "C",
    hint: "Use Pt = mcΔT.",
  },
  {
    id: "heat-q03",
    section: "heat-internal-energy",
    difficulty: "Applied",
    stem: "An electric heater is turned on in a closed room. It releases 1732 kJ of energy in a certain period of time. The total volume of air in the room is 200 m³. Estimate the increase in temperature of the air in the room. Assume that all the energy released by the heater is used to raise the temperature of the air inside the room and there is no energy loss from the room.\n\nGiven: density of air = 1.3 kg m⁻³; specific heat capacity of air = 1030 J kg⁻¹ °C⁻¹.",
    options: [
      { key: "A", text: "0.0647 °C" },
      { key: "B", text: "0.0841 °C" },
      { key: "C", text: "6.47 °C" },
      { key: "D", text: "8.41 °C" },
    ],
    answer: "C",
    hint: "Find the mass of air first, then use Q = mcΔT.",
  },
  {
    id: "heat-q04",
    section: "heat-internal-energy",
    difficulty: "Standard",
    stem: "An immersion heater of power 150 W is switched on for 2 minutes. How much energy is given out by the heater?",
    options: [
      { key: "A", text: "150 J" },
      { key: "B", text: "300 J" },
      { key: "C", text: "18 kJ" },
      { key: "D", text: "30 kJ" },
    ],
    answer: "C",
    hint: "Energy = power × time.",
  },
  {
    id: "heat-q05",
    section: "heat-internal-energy",
    difficulty: "Foundation",
    stem: "Which of the following substances has the highest specific heat capacity?",
    options: [
      { key: "A", text: "1 kg of water at 95 °C" },
      { key: "B", text: "2 kg of water at 70 °C" },
      { key: "C", text: "3 kg of water at 65 °C" },
      { key: "D", text: "All the substances above have the same specific heat capacity." },
    ],
    answer: "D",
    hint: "Specific heat capacity of water is the same at different temperatures and masses.",
  },
  {
    id: "heat-q06",
    section: "heat-internal-energy",
    difficulty: "Applied",
    stem: "Water flows at a rate of 0.5 kg per minute into a tube installed inside a furnace that heats the water uniformly. The temperatures of water at the inlet and outlet of the tube are 20 °C and 98 °C respectively.\n(Specific heat capacity of water = 4200 J kg⁻¹ °C⁻¹)\n\nWhat is the power of the furnace in heating the water?",
    options: [
      { key: "A", text: "1880 W" },
      { key: "B", text: "2730 W" },
      { key: "C", text: "164 000 W" },
      { key: "D", text: "206 000 W" },
    ],
    answer: "B",
    hint: "In 60 s, Pt = mcΔT for the water heated in one minute.",
  },
  {
    id: "heat-q07",
    section: "heat-internal-energy",
    difficulty: "Standard",
    stem: "Liquids X, Y and Z of equal mass are heated separately with the same power. The graph below shows the variation of the temperatures of the liquids with time. Let cX, cY and cZ be the specific heat capacities of X, Y and Z respectively.\n\nWhich of the following correctly shows the relation between cX, cY and cZ?",
    options: [
      { key: "A", text: "cX = cY > cZ" },
      { key: "B", text: "cX > cY > cZ" },
      { key: "C", text: "cX > cY = cZ" },
      { key: "D", text: "cX < cY = cZ" },
    ],
    answer: "C",
    hint: "For the same power, a smaller slope on the T–t graph means a larger specific heat capacity.",
  },
  {
    id: "heat-q08",
    section: "heat-internal-energy",
    difficulty: "Applied",
    stem: "Two identical foam cups, A and B, carry the same amount of water at 20 °C initially. Then, water in cups A and B is heated by electrical heaters of power 2P and P respectively for the same period of time. Assume no energy is lost to the surroundings.\n\nIf the final temperature of the water in cup A is 80 °C, find the final temperature of the water in cup B.",
    options: [
      { key: "A", text: "30 °C" },
      { key: "B", text: "40 °C" },
      { key: "C", text: "50 °C" },
      { key: "D", text: "60 °C" },
    ],
    answer: "C",
    hint: "With the same time, mass and c, ΔT is proportional to heater power.",
  },
  {
    id: "heat-q09",
    section: "heat-internal-energy",
    difficulty: "Applied",
    stem: "Liquid X of mass 2 kg is heated by an immersion heater for 10 minutes. The temperature of X rises from 20 °C to 30 °C. 1000 J of energy is lost to the surroundings in the process. The power of the heater is 100 W. Calculate the specific heat capacity of X.",
    options: [
      { key: "A", text: "2950 J kg⁻¹ °C⁻¹" },
      { key: "B", text: "3000 J kg⁻¹ °C⁻¹" },
      { key: "C", text: "3050 J kg⁻¹ °C⁻¹" },
      { key: "D", text: "5900 J kg⁻¹ °C⁻¹" },
    ],
    answer: "A",
    hint: "Energy supplied by heater = energy gained by liquid + energy lost to surroundings.",
  },
  {
    id: "heat-q10",
    section: "heat-internal-energy",
    difficulty: "Standard",
    stem: "A heater is used to heat up a 5-kg metal block. The temperature of the block rises from 25 °C to 35 °C. The heat capacity of the block is 100 J °C⁻¹. Assume that there is no energy loss to the surroundings. How much energy is supplied by the heater?",
    options: [
      { key: "A", text: "100 J" },
      { key: "B", text: "500 J" },
      { key: "C", text: "1000 J" },
      { key: "D", text: "5000 J" },
    ],
    answer: "C",
    hint: "Use Q = CΔT.",
  },
  {
    id: "cos-q01",
    section: "change-of-state",
    difficulty: "Standard",
    stem: "Two substances X and Y, of equal mass, are heated separately at the same power. They are initially at room temperature. The graph below shows how their temperatures vary with time.\n\nWhich of the following statements is incorrect?",
    options: [
      { key: "A", text: "The melting of X and the boiling of Y happens at the same temperature." },
      { key: "B", text: "When X starts boiling, Y just melts completely." },
      { key: "C", text: "X and Y require the same amount of energy to raise from room temperature to their melting points." },
      { key: "D", text: "The specific heat capacity of X in solid state is higher than that of Y." },
    ],
    answer: "D",
    hint: "Compare the slopes of the heating curves in the solid state before melting begins.",
  },
  {
    id: "cos-q02",
    section: "change-of-state",
    difficulty: "Applied",
    stem: "The diagram below shows the apparatus used for finding the specific latent heat of vaporization of a liquid.\n\nThe output of the heater is 200 W. The balance reading decreases by 15 g after the liquid has boiled for 300 s. If the heat lost to the surroundings is negligible, what is the specific latent heat of vaporization of the liquid?",
    options: [
      { key: "A", text: "4 × 10³ J kg⁻¹" },
      { key: "B", text: "1.2 × 10⁶ J kg⁻¹" },
      { key: "C", text: "4 × 10⁶ J kg⁻¹" },
      { key: "D", text: "6 × 10⁶ J kg⁻¹" },
    ],
    answer: "C",
    hint: "Use Pt = m lv with the mass of vapour produced.",
    image: {
      src: "./assets/cos-q02-lv-apparatus.png",
      alt: "Apparatus for finding specific latent heat of vaporization with heater, cup and balance",
      caption: "Fig · Latent heat of vaporization experiment",
    },
  },
  {
    id: "cos-q03",
    section: "change-of-state",
    difficulty: "Standard",
    stem: "Which of the following quantities can be used to find out the energy released as steam at 100 °C changes to water at 0 °C?\n(1) Heat capacity of water\n(2) Latent heat of vaporization of water\n(3) Latent heat of fusion of ice",
    options: [
      { key: "A", text: "(1) only" },
      { key: "B", text: "(2) only" },
      { key: "C", text: "(1) and (2) only" },
      { key: "D", text: "(1), (2) and (3)" },
    ],
    answer: "C",
    hint: "Condensation uses lv; cooling water from 100 °C to 0 °C uses mcΔT or heat capacity.",
  },
  {
    id: "cos-q04",
    section: "change-of-state",
    difficulty: "Applied",
    stem: "Ice at −5 °C is added to 0.5 kg of hot water at 98 °C. Assume that no energy is lost to the surroundings. If the final temperature of the mixture is 5 °C, what is the mass of ice used?\n(Specific heat capacity of water = 4200 J kg⁻¹ °C⁻¹; specific heat capacity of ice = 2100 J kg⁻¹ °C⁻¹; specific latent heat of fusion of ice = 3.34 × 10⁵ J kg⁻¹)",
    options: [
      { key: "A", text: "0.47 kg" },
      { key: "B", text: "0.53 kg" },
      { key: "C", text: "0.57 kg" },
      { key: "D", text: "0.62 kg" },
    ],
    answer: "B",
    hint: "Include warming ice to 0 °C, melting, and warming the melt to 5 °C.",
  },
  {
    id: "cos-q05",
    section: "change-of-state",
    difficulty: "Applied",
    stem: "A fish of mass 800 g at 20 °C is steamed. After 50 g of steam at 100 °C has condensed on the fish, estimate the temperature of the fish. Assume that the fish only absorbs energy from this mass of steam and its temperature is uniform throughout the process.\n(Specific heat capacity of fish = 3430 J kg⁻¹ °C⁻¹; specific latent heat of vaporization of water = 2.26 × 10⁶ J kg⁻¹)",
    options: [
      { key: "A", text: "41.2 °C" },
      { key: "B", text: "61.2 °C" },
      { key: "C", text: "63.9 °C" },
      { key: "D", text: "100 °C" },
    ],
    answer: "C",
    hint: "Energy lost by steam = latent heat released + cooling of condensed water.",
  },
  {
    id: "cos-q06",
    section: "change-of-state",
    difficulty: "Foundation",
    stem: "A substance is heated continuously and the variation of its temperature over time during the heating process is shown below.\n\nWhich of the following descriptions about the substance from t₁ to t₂ is/are correct?\n(1) Its temperature remains unchanged.\n(2) Its state of matter remains unchanged.\n(3) Its internal energy remains unchanged.",
    options: [
      { key: "A", text: "(1) only" },
      { key: "B", text: "(1) and (3) only" },
      { key: "C", text: "(2) and (3) only" },
      { key: "D", text: "(1), (2) and (3)" },
    ],
    answer: "A",
    hint: "During a horizontal section of a heating curve, temperature is constant but internal energy still increases.",
  },
  {
    id: "cos-q07",
    section: "change-of-state",
    difficulty: "Applied",
    stem: "Melting ice of mass m is added to a glass of coke of mass 3m. The final temperature of the mixture is 4 °C. Assume that no energy is lost to the surroundings. Find the initial temperature of the coke.\n(Specific heat capacity of coke = 5300 J kg⁻¹ °C⁻¹; specific heat capacity of water = 4200 J kg⁻¹ °C⁻¹; specific latent heat of fusion of ice = 3.34 × 10⁵ J kg⁻¹)",
    options: [
      { key: "A", text: "21.0 °C" },
      { key: "B", text: "22.1 °C" },
      { key: "C", text: "25.0 °C" },
      { key: "D", text: "26.1 °C" },
    ],
    answer: "D",
    hint: "Energy lost by coke = energy to melt ice + warm melt to 4 °C.",
  },
  {
    id: "cos-q08",
    section: "change-of-state",
    difficulty: "Standard",
    stem: "The following table shows the specific heat capacity and specific latent heat of fusion of water and copper.\n\n| | Specific heat capacity | Specific latent heat of fusion |\n|---|---|---|\n| Water | 4200 J kg⁻¹ °C⁻¹ | 3.34 × 10⁵ J kg⁻¹ |\n| Copper | 370 J kg⁻¹ °C⁻¹ | 2.1 × 10⁵ J kg⁻¹ |\n\nArrange the following in ascending order.\n\nE₁ = energy required to melt 1 kg of ice at 0 °C\n\nE₂ = energy required to raise the temperature of 1 kg of water by 1 °C\n\nE₃ = energy required to melt 1 kg of copper at its melting point\n\nE₄ = energy required to raise the temperature of 1 kg of copper by 1 °C",
    options: [
      { key: "A", text: "E₃ < E₁ < E₄ < E₂" },
      { key: "B", text: "E₃ < E₄ < E₂ < E₁" },
      { key: "C", text: "E₄ < E₃ < E₂ < E₁" },
      { key: "D", text: "E₄ < E₂ < E₃ < E₁" },
    ],
    answer: "D",
    hint: "Compare mcΔT values (1 °C rise) with m lf values for 1 kg.",
  },
  {
    id: "cos-q09",
    section: "change-of-state",
    difficulty: "Applied",
    stem: "Ken boils some water with a kettle. The water is heated from 15 °C to 100 °C in 10 minutes. If he forgets to shut it down, how long will it take to vaporize the water completely? Assume the water is heated at a constant power during the process.\n(Specific heat capacity of water = 4200 J kg⁻¹ °C⁻¹; specific latent heat of vaporization of water = 2.26 × 10⁶ J kg⁻¹)",
    options: [
      { key: "A", text: "About 50 minutes" },
      { key: "B", text: "About 60 minutes" },
      { key: "C", text: "About 70 minutes" },
      { key: "D", text: "Cannot be determined since the mass of water is not given" },
    ],
    answer: "B",
    hint: "Power is the same for both stages; mass cancels when comparing Pt = mcΔT and Pt = m lv.",
  },
  {
    id: "cos-q10",
    section: "change-of-state",
    difficulty: "Standard",
    stem: "The diagram below shows the apparatus used to find the specific latent heat of vaporization of water.\n\nWhich of the following factors will make the result obtained smaller than the true value?\n(1) Some energy supplied by the heater is lost to the surroundings.\n(2) Some water splashes out of the cup as it boils.\n(3) Some steam condenses and drips back into the cup.",
    options: [
      { key: "A", text: "(1) only" },
      { key: "B", text: "(2) only" },
      { key: "C", text: "(1) and (2) only" },
      { key: "D", text: "(1), (2) and (3)" },
    ],
    answer: "B",
    hint: "Lv = E/Δm; an overestimated mass loss gives a smaller calculated lv.",
    image: {
      src: "./assets/cos-q10-lv-apparatus.jpeg",
      alt: "Apparatus with joulemeter, heater and cup on a balance",
      caption: "Fig · Latent heat of vaporization setup",
    },
  },
  {
    id: "ht-q01",
    section: "heat-transfer",
    difficulty: "Foundation",
    stem: "Which of the following heat transfer processes involve(s) movements of molecules?\n(1) Conduction\n(2) Convection\n(3) Radiation",
    options: [
      { key: "A", text: "(1) only" },
      { key: "B", text: "(2) only" },
      { key: "C", text: "(1) and (2) only" },
      { key: "D", text: "(1), (2) and (3)" },
    ],
    answer: "C",
    hint: "Radiation does not require molecular movement in a medium.",
  },
  {
    id: "ht-q02",
    section: "heat-transfer",
    difficulty: "Foundation",
    stem: "Two objects are of different temperatures. Which of the following statements is/are correct?\n(1) There is heat transfer between the two objects when they are put in contact.\n(2) The colder one may have more internal energy.\n(3) The average kinetic energy of the particles in the two objects can be the same.",
    options: [
      { key: "A", text: "(1) only" },
      { key: "B", text: "(1) and (2) only" },
      { key: "C", text: "(2) and (3) only" },
      { key: "D", text: "(1), (2) and (3)" },
    ],
    answer: "B",
    hint: "Temperature measures average kinetic energy; internal energy also depends on mass.",
  },
  {
    id: "ht-q03",
    section: "heat-transfer",
    difficulty: "Foundation",
    stem: "In which of the following media can conduction take place?\n(1) Metal\n(2) Glass\n(3) Water",
    options: [
      { key: "A", text: "(1) only" },
      { key: "B", text: "(1) and (2) only" },
      { key: "C", text: "(2) and (3) only" },
      { key: "D", text: "(1), (2) and (3)" },
    ],
    answer: "D",
    hint: "Conduction can occur in solids and fluids.",
  },
  {
    id: "ht-q04",
    section: "heat-transfer",
    difficulty: "Foundation",
    stem: "Which of the following transfer processes of heat can take place in a hot fluid?\n(1) Conduction\n(2) Convection\n(3) Radiation",
    options: [
      { key: "A", text: "(1) only" },
      { key: "B", text: "(3) only" },
      { key: "C", text: "(1) and (2) only" },
      { key: "D", text: "(1), (2) and (3)" },
    ],
    answer: "D",
    hint: "All three can occur in a fluid unless radiation is blocked.",
  },
  {
    id: "ht-q05",
    section: "heat-transfer",
    difficulty: "Foundation",
    stem: "Which of the following actions cannot increase the rate of heat loss by radiation of a hot object?",
    options: [
      { key: "A", text: "Increase its temperature" },
      { key: "B", text: "Increase its surface area" },
      { key: "C", text: "Paint its surface silvery" },
      { key: "D", text: "Paint its surface dull black" },
    ],
    answer: "C",
    hint: "Silvery surfaces are poor radiators.",
  },
  {
    id: "ht-q06",
    section: "heat-transfer",
    difficulty: "Standard",
    stem: "An immersion heater is put in a glass of water. Which of the following diagrams best shows the convection current in the glass?",
    options: [
      { key: "A", text: "Diagram A" },
      { key: "B", text: "Diagram B" },
      { key: "C", text: "Diagram C" },
      { key: "D", text: "Diagram D" },
    ],
    answer: "A",
    hint: "Hot water rises above the heater; cooler water moves in to replace it.",
    image: {
      src: "./assets/ht-q06-convection.png",
      alt: "Four diagrams A–D showing convection currents in a glass of water with an immersion heater",
      caption: "Fig · Convection in a glass of water",
    },
  },
  {
    id: "ht-q07",
    section: "heat-transfer",
    difficulty: "Foundation",
    stem: "The following picture shows a fan heat sink of a computer that prevents the processor from overheating.\n\nWhich of the following heat transfer processes help cool the processor?\n(1) Conduction\n(2) Convection\n(3) Radiation",
    options: [
      { key: "A", text: "(1) and (2) only" },
      { key: "B", text: "(1) and (3) only" },
      { key: "C", text: "(2) and (3) only" },
      { key: "D", text: "(1), (2) and (3)" },
    ],
    answer: "D",
    hint: "Heat moves through the metal by conduction, then leaves by forced convection and radiation.",
    image: {
      src: "./assets/ht-q07-heatsink.jpeg",
      alt: "CPU heat sink with fan and metal fins",
      caption: "Fig · Fan heat sink",
    },
  },
  {
    id: "ht-q08",
    section: "heat-transfer",
    difficulty: "Foundation",
    stem: "Which of the following statements about radiation is/are correct?\n(1) Dull black surfaces can slow down the rate of heat loss by radiation.\n(2) Dull black surfaces are good absorbers of radiation.\n(3) Shiny surfaces do not absorb radiation.",
    options: [
      { key: "A", text: "(1) only" },
      { key: "B", text: "(2) only" },
      { key: "C", text: "(1) and (3) only" },
      { key: "D", text: "(2) and (3) only" },
    ],
    answer: "B",
    hint: "Dull black surfaces are good absorbers and good emitters; shiny surfaces are poor absorbers but not zero.",
  },
  {
    id: "ht-q09",
    section: "heat-transfer",
    difficulty: "Standard",
    stem: "The following figure shows the structure of a thermos flask.\n\nWhich of the components of the thermos flask is best at:\n• preventing heat loss by conduction\n• preventing heat loss by convection\n• preventing heat loss by radiation",
    options: [
      { key: "A", text: "Vacuum / vacuum / vacuum" },
      { key: "B", text: "Vacuum / plastic stopper / silvery glass walls" },
      { key: "C", text: "Plastic stopper / insulated support / silvery glass walls" },
      { key: "D", text: "Insulated support / vacuum / plastic stopper" },
    ],
    answer: "B",
    hint: "Vacuum stops conduction and convection between the walls; silvery surfaces reduce radiation.",
    image: {
      src: "./assets/ht-q09-thermos.jpeg",
      alt: "Cross-section of a thermos flask showing vacuum, stopper and silvery walls",
      caption: "Fig · Thermos flask structure",
    },
  },
  {
    id: "ht-q10",
    section: "heat-transfer",
    difficulty: "Foundation",
    stem: "A metal block and a wooden block are at the same temperature of 20 °C. Which of the following statements is/are correct?\n(1) Conduction does not take place when you touch the wooden block.\n(2) The metal block feels colder because it is a better conductor of heat than the wooden block.\n(3) When the blocks are put in contact, heat flows from the wooden block to the metal block.",
    options: [
      { key: "A", text: "(1) only" },
      { key: "B", text: "(2) only" },
      { key: "C", text: "(1) and (2) only" },
      { key: "D", text: "(2) and (3) only" },
    ],
    answer: "B",
    hint: "At the same temperature there is no net heat flow between the blocks.",
  },
];
