/** S3 Optics Ch.3 — Light & Lens */
export const QUIZ_SECTIONS = [
  {
    "id": "reflection",
    "label": "Reflection"
  },
  {
    "id": "refraction-snells-law",
    "label": "Refraction and Snell's Law"
  },
  {
    "id": "total-internal-reflection",
    "label": "Total Internal Reflection"
  },
  {
    "id": "convex-lens",
    "label": "Convex Lens"
  },
  {
    "id": "magnification-lens-formula",
    "label": "Magnification and Lens Formula"
  },
  {
    "id": "concave-lens",
    "label": "Concave Lens"
  }
];

export const QUIZ_ITEMS = [
  {"id": "ch31-r01", "section": "reflection", "difficulty": "Standard", "stem": "Object O is placed in front of two plane mirrors as shown in the following diagram.", "options": [{"key": "A", "text": "At P only"}, {"key": "B", "text": "At Q only"}, {"key": "C", "text": "At P and Q only"}, {"key": "D", "text": "At P and R only"}], "answer": "D", "hint": "Object O is placed in front of two plane mirrors as shown in the following diagram.", "image": {"src": "./assets/ch31-r01-fig.png", "alt": "Diagram for ch31-r01", "caption": "Fig · ch31-r01"}},
  {"id": "ch31-r02", "section": "reflection", "difficulty": "Foundation", "stem": "Simon stands in front of a plane mirror as shown. There is an opaque obstacle between Simon and the mirror. Which of the following statements is/are correct? (1)When he stands at the position shown, he cannot see the image of his shoes in the mirror. (2)If he walks closer to the obstacle, he may see the image of his shoes in the mirror. (3)If he walks away from the obstacle, he may see the image of his shoes in the mirror.", "options": [{"key": "A", "text": "(1) only"}, {"key": "B", "text": "(2) only"}, {"key": "C", "text": "(3) only"}, {"key": "D", "text": "(1) and (2) only"}], "answer": "A", "hint": "As long as the obstacle is between him and the mirror, light from his shoes is always blocked by the obstacle and cannot reach the mirror. Therefore (1) is correct; (2) and (3) are incorrect.", "image": {"src": "./assets/ch31-r02-fig.png", "alt": "Diagram for ch31-r02", "caption": "Fig · ch31-r02"}},
  {"id": "ch31-r03", "section": "reflection", "difficulty": "Standard", "stem": "The figure shows a student standing in front of a wall mirror. What is the minimum height of the mirror above the floor so that she can see her full image in the mirror?", "options": [{"key": "A", "text": "40 cm"}, {"key": "B", "text": "54 cm"}, {"key": "C", "text": "80 cm"}, {"key": "D", "text": "94 cm"}], "answer": "D", "hint": "The bottom edge of the mirror must be at half the height of her eyes above the floor.", "image": {"src": "./assets/ch31-r03-fig.png", "alt": "Diagram for ch31-r03", "caption": "Fig · ch31-r03"}},
  {"id": "ch31-r04", "section": "reflection", "difficulty": "Standard", "stem": "Heidi is standing between two parallel mirrors, M1 and M2, with their reflective surfaces facing each other as shown below. When Heidi looks at M1, she sees multiple images in the mirror. Which of the following is/are the image(s) of Heidi seen in M1?", "options": [{"key": "A", "text": "I1 only"}, {"key": "B", "text": "I1 and I2 only"}, {"key": "C", "text": "I1 and I3 only"}, {"key": "D", "text": "I1, I3 and I4 only"}], "answer": "C", "hint": "I1 is the image of Heidi formed by mirror M1. There is also an image I' of Heidi 1 m behind M2 formed by mirror M2.", "image": {"src": "./assets/ch31-r04-fig.png", "alt": "Diagram for ch31-r04", "caption": "Fig · ch31-r04"}},
  {"id": "ch31-r05", "section": "reflection", "difficulty": "Standard", "stem": "Which of the following correctly shows the image of the letter 'P' as seen in the mirror?", "options": [{"key": "A", "text": "Option A"}, {"key": "B", "text": "Option B"}, {"key": "C", "text": "Option C"}, {"key": "D", "text": "Option D"}], "answer": "C", "hint": "Which of the following correctly shows the image of the letter 'P' as seen in the mirror?", "images": [{"src": "./assets/ch31-r05-fig-1.png", "alt": "Diagram for ch31-r05", "caption": "Fig · ch31-r05 (1/2)"}, {"src": "./assets/ch31-r05-fig-2.png", "alt": "Diagram for ch31-r05", "caption": "Fig · ch31-r05 (2/2)"}]},
  {"id": "ch31-r06", "section": "reflection", "difficulty": "Standard", "stem": "What is the actual time at this instant?", "options": [{"key": "A", "text": "2:58"}, {"key": "B", "text": "3:02"}, {"key": "C", "text": "8:58"}, {"key": "D", "text": "12:13"}], "answer": "B", "hint": "What is the actual time at this instant?", "image": {"src": "./assets/ch31-r06-fig.png", "alt": "Diagram for ch31-r06", "caption": "Fig · ch31-r06"}},
  {"id": "ch31-r07", "section": "reflection", "difficulty": "Foundation", "stem": "Which of the following statements about the image formed by a plane mirror is/are correct? (1)The image cannot be projected on a screen. (2)Light rays entering the eyes do not come from the image. (3)The image is behind the mirror.", "options": [{"key": "A", "text": "(1) only"}, {"key": "B", "text": "(1) and (3) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "D", "hint": "Light rays entering the eyes are emitted or reflected from the object. They do not come from the image. ∴ (2) is correct."},
  {"id": "ch31-r08", "section": "reflection", "difficulty": "Standard", "stem": "In the figure below, what is the angle of reflection of the ray after being reflected by mirror ?", "options": [{"key": "A", "text": "40"}, {"key": "B", "text": "45"}, {"key": "C", "text": "50"}, {"key": "D", "text": "55"}], "answer": "A", "hint": "M2M13010060°60°30°θirM2M13010060°60°30°θir θ i r θ i r", "image": {"src": "./assets/ch31-r08-fig.png", "alt": "Diagram for ch31-r08", "caption": "Fig · ch31-r08"}},
  {"id": "ch31-r09", "section": "reflection", "difficulty": "Standard", "stem": "John is in front of a plane mirror. If the mirror moves away from him at a speed of 2 m s⁻¹, at what speed does his image move away from him?", "options": [{"key": "A", "text": "1 m s⁻¹"}, {"key": "B", "text": "2 m s⁻¹"}, {"key": "C", "text": "4 m s⁻¹"}, {"key": "D", "text": "8 m s⁻¹"}], "answer": "C", "hint": "John is in front of a plane mirror. If the mirror moves away from him at a speed of 2 m s⁻¹, at what speed does his image move away from him?"},
  {"id": "ch31-r10", "section": "reflection", "difficulty": "Standard", "stem": "A girl with her eyes 1.5 m above the ground stands in front of a wall, as shown in the figure below. If a small mirror is to be hung on the wall, how high should it be placed so that the girl can see the light in the mirror?", "options": [{"key": "A", "text": "1.50 m above the ground"}, {"key": "B", "text": "1.63 m above the ground"}, {"key": "C", "text": "1.75 m above the ground"}, {"key": "D", "text": "1.83 m above the ground"}], "answer": "D", "hint": "The light is 3 m away from the mirror, so the image of the light is 3 m behind the mirror. 1 mh1.5 m3 mES1 mh1.5 m3 mES h h = h = 0.33 m = 1.5 + 0.33 = 1.83 m The mirror should be placed 1.83 m above the ground. --", "image": {"src": "./assets/ch31-r10-fig.png", "alt": "Diagram for ch31-r10", "caption": "Fig · ch31-r10"}},
  {"id": "ch32-f01", "section": "refraction-snells-law", "difficulty": "Applied", "stem": "The figure shows a light ray passing through three media X, Y and Z. Which of the following statements about the three media are correct? (1)Z is optically denser than X. (2)Light travels the fastest in X. (3)Y has the greatest refractive index.", "options": [{"key": "A", "text": "(1) and (2) only"}, {"key": "B", "text": "(1) and (3) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "D", "hint": "Let i1, i2 and r1, r2 be the angles of incidence and angles of refractions in the 1st and the 2nd refraction. r1 = i2 1st refraction: nX sin i1 = nY sin r1 2nd refraction: nZ sin r2 = nY sin i2 = nY sin r1 = nX sin i1 i1 r2 sin i1 sin r2 nX nZ ∴ (1) is correct. i1 r1 sin i1 sin r1 nX nY The refractive index of X is the", "image": {"src": "./assets/ch32-f01-fig.png", "alt": "Diagram for ch32-f01", "caption": "Fig · ch32-f01"}},
  {"id": "ch32-f02", "section": "refraction-snells-law", "difficulty": "Applied", "stem": "The figure shows a light ray refracted at the boundary between medium X and medium Y. The refractive index of X is 1.77. What is the refractive index of Y?", "options": [{"key": "A", "text": "1.16"}, {"key": "B", "text": "1.53"}, {"key": "C", "text": "1.70"}, {"key": "D", "text": "2.05"}], "answer": "B", "hint": "What is the refractive index of Y?", "image": {"src": "./assets/ch32-f02-fig.png", "alt": "Diagram for ch32-f02", "caption": "Fig · ch32-f02"}},
  {"id": "ch32-f03", "section": "refraction-snells-law", "difficulty": "Standard", "stem": "Which of the following are examples of refraction? (1)A chopstick appears bent when dipped in water. (2)A distorted image of a tree is observed on a ruffled water surface. (3)A goldfish in a tank appears nearer and bigger than it really is.", "options": [{"key": "A", "text": "(1) and (2) only"}, {"key": "B", "text": "(1) and (3) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "B", "hint": "Which of the following are examples of refraction? (1)A chopstick appears bent when dipped in water. (2)A distorted image of a tree is observed on a ruffled water surface. (3)A gol"},
  {"id": "ch32-f04", "section": "refraction-snells-law", "difficulty": "Applied", "stem": "The following figure shows a light ray travelling from medium X to a vacuum. What is the refractive index of medium X?", "options": [{"key": "A", "text": "sin β / cos θ"}, {"key": "B", "text": "cos θ / sin β"}, {"key": "C", "text": "sin θ / sin β"}, {"key": "D", "text": "cos β / sin θ"}], "answer": "A", "hint": "What is the refractive index of ?", "image": {"src": "./assets/ch32-f04-fig.png", "alt": "Diagram for ch32-f04", "caption": "Fig · ch32-f04"}},
  {"id": "ch32-f05", "section": "refraction-snells-law", "difficulty": "Standard", "stem": "The figure shows a light ray travelling from medium Y to medium X. What is the angle of refraction?", "options": [{"key": "A", "text": "10.5"}, {"key": "B", "text": "18.1"}, {"key": "C", "text": "21.5"}, {"key": "D", "text": "26.1"}], "answer": "C", "hint": "What is the angle of refraction?", "image": {"src": "./assets/ch32-f05-fig.png", "alt": "Diagram for ch32-f05", "caption": "Fig · ch32-f05"}},
  {"id": "ch32-f06", "section": "refraction-snells-law", "difficulty": "Applied", "stem": "A ray of light travels from medium X to medium Y as shown. The speed of light in air and medium X are 3 × 10⁸ m s⁻¹ and 2.5 × 10⁸ m s⁻¹ respectively. Find the refractive index of medium Y.", "options": [{"key": "A", "text": "1.27"}, {"key": "B", "text": "1.29"}, {"key": "C", "text": "1.52"}, {"key": "D", "text": "1.83"}], "answer": "D", "hint": "Find the refractive index of . 4025medium Xmedium Y4025medium Xmedium Y", "image": {"src": "./assets/ch32-f06-fig.png", "alt": "Diagram for ch32-f06", "caption": "Fig · ch32-f06"}},
  {"id": "ch32-f07", "section": "refraction-snells-law", "difficulty": "Foundation", "stem": "Which of the following statements about the laws of refraction is/are correct? (1)The angle of refraction r is always equal to the angle of incidence i. (2)The ratio of the sine of the angle of incidence i to the sine of the angle of refraction r is always equal to 1, i.e. sin i / sin r = 1. (3)The incident ray, the refracted ray and the normal all lie in the same plane.", "options": [{"key": "A", "text": "(3) only"}, {"key": "B", "text": "(1) and (2) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "A", "hint": "Which of the following statements about the laws of refraction is/are correct? (1)The angle of refraction r is always equal to the angle of incidence i. (2)The ratio of the sine of"},
  {"id": "ch32-f08", "section": "refraction-snells-law", "difficulty": "Standard", "stem": "Three light rays enter an air bubble in water. C is the centre of the bubble. Which of the paths shown below is/are correct?", "options": [{"key": "A", "text": "(2) only"}, {"key": "B", "text": "(1) and (2) only"}, {"key": "C", "text": "(1) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "B", "hint": "Three light rays enter an air bubble in water. C is the centre of the bubble. Which of the paths shown below is/are correct? water air water air", "image": {"src": "./assets/ch32-f08-fig.png", "alt": "Diagram for ch32-f08", "caption": "Fig · ch32-f08"}},
  {"id": "ch32-f09", "section": "refraction-snells-law", "difficulty": "Standard", "stem": "The figure below shows the apparent position of a goldfish as seen by an observer above water. Where is the actual position of the goldfish?", "options": [{"key": "A", "text": "Option A"}, {"key": "B", "text": "Option B"}, {"key": "C", "text": "Option C"}, {"key": "D", "text": "Option D"}], "answer": "D", "hint": "Where is the actual position of the goldfish? observer's eyeapparent position of goldfishobserver's eyeapparent position of goldfish observer's eye apparent position of goldfish ob", "image": {"src": "./assets/ch32-f09-fig.png", "alt": "Diagram for ch32-f09", "caption": "Fig · ch32-f09"}},
  {"id": "ch32-f10", "section": "refraction-snells-law", "difficulty": "Foundation", "stem": "Which of the following statements about this phenomenon is/are correct? (1)White light is composed of a mixture of colours. (2)Different colours of light travel at different speeds in glass. (3)Green light is refracted more than red light in passing through the prism.", "options": [{"key": "A", "text": "(1) only"}, {"key": "B", "text": "(1) and (2) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "D", "hint": "White light is composed of a mixture of coloured lights. A beam of white light is dispersed into lights of different colours when it passes through a glass prism as lights of different colours travel at different speeds in glass. ∴ (1) and (2) are correct. Green light is refracted more than red light in passing through"},
  {"id": "ch33-t01", "section": "total-internal-reflection", "difficulty": "Standard", "stem": "The figure shows light refracted at a boundary between water and air. What is β?", "options": [{"key": "A", "text": "14.4"}, {"key": "B", "text": "21.3"}, {"key": "C", "text": "35.6"}, {"key": "D", "text": "42.0"}], "answer": "C", "hint": "Use Snell's law and the geometry of the triangle formed by the refracted ray and the boundaries.", "image": {"src": "./assets/ch33-t01-fig.png", "alt": "Diagram for ch33-t01", "caption": "Fig · ch33-t01"}},
  {"id": "ch33-t02", "section": "total-internal-reflection", "difficulty": "Standard", "stem": "Why does the air bubble appear silvery?", "options": [{"key": "A", "text": "Total internal reflection occurs when light rays travel from above the water surface to the water."}, {"key": "B", "text": "Total internal reflection occurs when light rays travel from water to above the water surface."}, {"key": "C", "text": "Total internal reflection occurs when light rays travel from water to the air bubble."}, {"key": "D", "text": "Total internal reflection occurs when light rays travel from the air bubble to water."}], "answer": "C", "hint": "Total internal reflection occurs only when light travels from an optically denser medium to an optically less dense medium. In this case, water is the optically denser medium. ∴ A and D are incorrect. Total internal reflection may occur when light rays travel from water to above the water surface, but the light rays wo", "image": {"src": "./assets/ch33-t02-fig.png", "alt": "Diagram for ch33-t02", "caption": "Fig · ch33-t02"}},
  {"id": "ch33-t03", "section": "total-internal-reflection", "difficulty": "Standard", "stem": "The figure shows a light ray incident on a semicircular glass block. Which of the following correctly describes what happens to the light ray at the curved surface?", "options": [{"key": "A", "text": "reflection only."}, {"key": "B", "text": "refraction only."}, {"key": "C", "text": "total internal reflection only."}, {"key": "D", "text": "refraction and total internal reflection."}], "answer": "D", "hint": "Refer to the figure."},
  {"id": "ch33-t04", "section": "total-internal-reflection", "difficulty": "Standard", "stem": "Which of the following instruments make(s) use of total internal reflection of light? (1)Optical fibre (2)Plane mirror (3)Prisms in a periscope", "options": [{"key": "A", "text": "(1) only"}, {"key": "B", "text": "(1) and (3) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "B", "hint": "Which of the following instruments make(s) use of total internal reflection of light? (1)Optical fibre (2)Plane mirror (3)Prisms in a periscope"},
  {"id": "ch33-t05", "section": "total-internal-reflection", "difficulty": "Standard", "stem": "The figure shows a light ray travelling from medium X to medium Y. Which of the following statements is/are correct? (1)Medium X is optically denser than medium Y. (2)Light travels faster in medium Y than in medium X. (3)Medium Y is air.", "options": [{"key": "A", "text": "(2) only"}, {"key": "B", "text": "(1) and (2) only"}, {"key": "C", "text": "(1) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "A", "hint": "(2)Light travels faster in than in . (3) is air.", "image": {"src": "./assets/ch33-t05-fig.png", "alt": "Diagram for ch33-t05", "caption": "Fig · ch33-t05"}},
  {"id": "ch33-t06", "section": "total-internal-reflection", "difficulty": "Standard", "stem": "What is/are the advantage(s) of right-angled prisms over plane glass mirrors in making periscopes? (1)The image is erect. (2)Multiple images are not formed. (3)The image is of the same size as the object.", "options": [{"key": "A", "text": "(2) only"}, {"key": "B", "text": "(1) and (3) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "A", "hint": "What is/are the advantage(s) of right-angled prisms over plane glass mirrors in making periscopes? (1)The image is erect. (2)Multiple images are not formed. (3)The image is of the "},
  {"id": "ch33-t07", "section": "total-internal-reflection", "difficulty": "Standard", "stem": "Which of the diagrams are correct? (1) (2) (3)", "options": [{"key": "A", "text": "(1) and (2) only"}, {"key": "B", "text": "(1) and (3) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "B", "hint": "When a light ray travels from air to an optically denser medium (glass), it bends towards the normal. ∴ (1) is correct. When a light ray travels from air to an optically denser medium (glass), total internal reflection will never occur. ∴ (2) is incorrect. When a light ray travels from glass to an optically less dense ", "image": {"src": "./assets/ch33-t07-fig.png", "alt": "Diagram for ch33-t07", "caption": "Fig · ch33-t07"}},
  {"id": "ch33-t08", "section": "total-internal-reflection", "difficulty": "Standard", "stem": "Which of the following ray diagrams is correct?", "options": [{"key": "B", "text": "60306030"}, {"key": "C", "text": "60306030"}, {"key": "D", "text": "60306030"}], "answer": "C", "hint": "Which of the following ray diagrams is correct?", "images": [{"src": "./assets/ch33-t08-fig-1.png", "alt": "Diagram for ch33-t08", "caption": "Fig · ch33-t08 (1/2)"}, {"src": "./assets/ch33-t08-fig-2.png", "alt": "Diagram for ch33-t08", "caption": "Fig · ch33-t08 (2/2)"}]},
  {"id": "ch33-t09", "section": "total-internal-reflection", "difficulty": "Applied", "stem": "Which of the following statements about total internal reflection of light is/are correct? (1)It occurs only when light travels from glass to air. (2)It will never occur if light travels from air to glass. (3)It will occur if light travels from a medium with a refractive index of 1.6 to air at an angle of incidence of 35.", "options": [{"key": "A", "text": "(1) only"}, {"key": "B", "text": "(2) only"}, {"key": "C", "text": "(1) and (3) only"}, {"key": "D", "text": "(2) and (3) only"}], "answer": "B", "hint": "Total internal reflection occurs only when light travels from an optically denser medium to an optically less dense medium. ∴ (1) is incorrect while (2) is correct. For (3), nm sin m = na sin a 1.6 sin C = 1 sin 90"},
  {"id": "ch33-t10", "section": "total-internal-reflection", "difficulty": "Applied", "stem": "As shown below, a small fish hides under the centre of a floating circular dish with a diameter of 2 m. If the fish moves vertically downwards from the water surface, how far can it move down the water before somebody above the water can see it? Given: refractive index of water = 1.33", "options": [{"key": "A", "text": "0.53 m"}, {"key": "B", "text": "0.66 m"}, {"key": "C", "text": "0.88 m"}, {"key": "D", "text": "1.14 m"}], "answer": "C", "hint": "Light from the fish is totally internally reflected when the angle of incidence is larger than the critical angle. nw sin w= na sin a 1.33 sin C = 1 sin 90 Let d be the maximum distance that the fish can move down before somebody above the water can see it. tan 48.8 = d = 0.88 m", "image": {"src": "./assets/ch33-t10-fig.png", "alt": "Diagram for ch33-t10", "caption": "Fig · ch33-t10"}},
  {"id": "ch34-c01", "section": "convex-lens", "difficulty": "Applied", "stem": "Which of the following statements about lens L shown in the figure below is/are correct? (1)Lens L is a convex lens. (2)Lens L has only one principal focus. (3)The focal length of lens L equals distance d.", "options": [{"key": "A", "text": "(1) only"}, {"key": "B", "text": "(3) only"}, {"key": "C", "text": "(1) and (2) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "A", "hint": "Which of the following statements about lens L shown in the figure below is/are correct? Ld Ld d d (1)Lens L is a . (2)Lens L has only one principal focus. (3)The focal length of l", "image": {"src": "./assets/ch34-c01-fig.png", "alt": "Diagram for ch34-c01", "caption": "Fig · ch34-c01"}},
  {"id": "ch34-c02", "section": "convex-lens", "difficulty": "Standard", "stem": "In the figure below, lens L is a convex lens and F is its principal focus. Which of the rays is wrongly drawn?", "options": [{"key": "A", "text": "P"}, {"key": "B", "text": "Q"}, {"key": "C", "text": "R"}, {"key": "D", "text": "S"}], "answer": "A", "hint": "FLPQRS FLPQRS", "image": {"src": "./assets/ch34-c02-fig.png", "alt": "Diagram for ch34-c02", "caption": "Fig · ch34-c02"}},
  {"id": "ch34-c03", "section": "convex-lens", "difficulty": "Applied", "stem": "An object is 10 cm away from a convex lens. The focal length of the lens is 15 cm. The image formed is", "options": [{"key": "A", "text": "real, erect and magnified."}, {"key": "B", "text": "virtual, inverted and diminished."}, {"key": "C", "text": "real, inverted and magnified."}, {"key": "D", "text": "virtual, erect and magnified."}], "answer": "D", "hint": "An object is away from a . The focal length of the lens is . The image formed is", "image": {"src": "./assets/ch34-c03-fig.png", "alt": "Diagram for ch34-c03", "caption": "Fig · ch34-c03"}},
  {"id": "ch34-c04", "section": "convex-lens", "difficulty": "Standard", "stem": "P is an emergent ray from a lens as shown below. F and F' are the principal foci of the lens. Which of the following rays is a possible incident ray?", "options": [{"key": "A", "text": "Ray w"}, {"key": "B", "text": "Ray x"}, {"key": "C", "text": "Ray y"}, {"key": "D", "text": "Ray z"}], "answer": "A", "hint": "Which of the following rays is a possible incident ray?", "image": {"src": "./assets/ch34-c04-fig.png", "alt": "Diagram for ch34-c04", "caption": "Fig · ch34-c04"}},
  {"id": "ch34-c05", "section": "convex-lens", "difficulty": "Foundation", "stem": "Which of the following statements about the image formed by a is/are correct? (1)If the image is virtual, it must be erect. (2)If the image is real, it can be either erect or inverted. (3)If the image is real, it can be either magnified or diminished.", "options": [{"key": "A", "text": "(1) only"}, {"key": "B", "text": "(1) and (3) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "B", "hint": "Which of the following statements about the image formed by a is/are correct? (1)If the image is virtual, it must be erect. (2)If the image is real, it can be either erect or inver"},
  {"id": "ch34-c06", "section": "convex-lens", "difficulty": "Applied", "stem": "Which of the following statements is/are correct? (1)The lens is a . (2)If the lens is moved further away from the object, the image will become smaller. (3)If the lens is replaced by the same type of lens with a shorter focal length, the image will become smaller.", "options": [{"key": "A", "text": "(1) only"}, {"key": "B", "text": "(1) and (2) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "D", "hint": "The image is real as it can be captured on a screen. Only a can form a magnified/real image. A magnified real image is formed when the object distance lies between f and 2f, where f is the focal length of the lens."},
  {"id": "ch34-c07", "section": "convex-lens", "difficulty": "Standard", "stem": "If F and F' are the principal foci of a convex lens, which of the following ray diagrams is/are incorrect? (1) (2) (3)", "options": [{"key": "A", "text": "(3) only"}, {"key": "B", "text": "(1) and (2) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "D", "hint": "If F and F' are the principal foci of a , which of the following ray diagrams is/are incorrect? (1) (2) (3)", "image": {"src": "./assets/ch34-c07-fig.png", "alt": "Diagram for ch34-c07", "caption": "Fig · ch34-c07"}},
  {"id": "ch34-c08", "section": "convex-lens", "difficulty": "Standard", "stem": "Which of the following correctly describes how the image changes?", "options": [{"key": "A", "text": "Magnified, erect magnified, inverted diminished, inverted"}, {"key": "B", "text": "Magnified, erect magnified, inverted more magnified, inverted"}, {"key": "C", "text": "Magnified, erect diminished, inverted more diminished, inverted"}, {"key": "D", "text": "Magnified, erect diminished, erect more diminished, erect"}], "answer": "A", "hint": "Let f be the focal length of the lens. When the object distance becomes larger than f, the image becomes magnified and inverted. When the object distance becomes larger than 2f, the image becomes diminished and inverted. 9. The figure below shows an experiment set-up. A clear image is formed on the screen when the and ", "image": {"src": "./assets/ch34-c08-fig.png", "alt": "Diagram for ch34-c08", "caption": "Fig · ch34-c08"}},
  {"id": "ch34-c09", "section": "convex-lens", "difficulty": "Applied", "stem": "Which of the following statements are correct? (1)The lens is convex. (2)The image formed is real. (3)The image distance is equal to the focal length.", "options": [{"key": "A", "text": "(1) and (2) only"}, {"key": "B", "text": "(1) and (3) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "D", "hint": "Parallel incident rays converge only after passing through a . ∴ (1) is correct. When rays from a distant object pass through a , a real image is formed on the focal plane. ∴ (2) and (3) are correct.", "image": {"src": "./assets/ch34-c09-fig.png", "alt": "Diagram for ch34-c09", "caption": "Fig · ch34-c09"}},
  {"id": "ch34-c10", "section": "convex-lens", "difficulty": "Applied", "stem": "Which of the following statements about the experiment is/are correct? (1)The focal length of the is equal to the distance between the and the lamp-housing. (2)The brightness and shape of the image will not change if the plane mirror is moved a little bit backwards. (3)The image will be larger if the experiment is repeated by using another with a shorter focal length.", "options": [{"key": "A", "text": "(1) only"}, {"key": "B", "text": "(1) and (2) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "B", "hint": "Only when the object is located at the principal focus of the , rays from the object are parallel to the after passing through the lens. These parallel rays are reflected by the plane mirror and then converge to the principal focus of the lens after passing through the lens once again. ∴ (1) is correct. The reflection "},
  {"id": "ch35-m01", "section": "magnification-lens-formula", "difficulty": "Standard", "stem": "The graph shows the variation of image distance v with object distance u for a convex lens. Which of the following statements is/are correct? (1)The focal length of the lens is 5 cm. (2)The value of x is 5. (3)The slope of the graph is 1.", "options": [{"key": "A", "text": "(1) only"}, {"key": "B", "text": "(2) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "B", "hint": "= + ……(*) ∴ (3) is incorrect. From the graph, when = 0, = 5 m1. Substitute the values into (*), 5 = 0 + f = 0.2 m ∴ (1) is incorrect. From the graph, when = 0, = x m1. Substitute the values into (*), 0 = x + x = 5 ∴ (2) is correct. v v If another of greater refractive index is used, which of the following graphs (in do", "image": {"src": "./assets/ch35-m01-fig.png", "alt": "Diagram for ch35-m01", "caption": "Fig · ch35-m01"}},
  {"id": "ch35-m02", "section": "magnification-lens-formula", "difficulty": "Standard", "stem": "Fig. a and Fig. b show the experimental set-up and the m–v graph for a convex lens. If another convex lens of greater refractive index is used, which of the following graphs (in dotted line) best shows the new m–v graph?", "options": [{"key": "A", "text": "3.75 cm, diverging lens"}, {"key": "B", "text": "3.75 cm, converging lens"}, {"key": "C", "text": "15 cm, diverging lens"}, {"key": "D", "text": "15 cm, converging lens"}], "answer": "C", "hint": "v v", "images": [{"src": "./assets/ch35-m02-fig-1.png", "alt": "Diagram for ch35-m02", "caption": "Fig · ch35-m02 (1/2)"}, {"src": "./assets/ch35-m02-fig-2.png", "alt": "Diagram for ch35-m02", "caption": "Fig · ch35-m02 (2/2)"}]},
  {"id": "ch35-m03", "section": "magnification-lens-formula", "difficulty": "Standard", "stem": "An object is placed 5 cm in front of a convex lens with a focal length of 3 cm. In applying the lens formula to find the position of the image, which of the following statements is/are correct? (1)f is 3 cm. (2)u is +5 cm. (3)The image is 1.875 cm from the lens on the same side as the object.", "options": [{"key": "A", "text": "(2) only"}, {"key": "B", "text": "(1) and (3) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "A", "hint": "f is positive for a . Therefore, f is + . ∴ (1) is incorrect. u is always positive. ∴ (2) is correct."},
  {"id": "ch35-m04", "section": "magnification-lens-formula", "difficulty": "Applied", "stem": "An object 7 cm tall is placed in front of a lens and the image formed is 5 cm tall. Which of the following may be the lens used? (1)Convex lens of focal length 2.92 cm (2)Convex lens of focal length 17.5 cm (3)Concave lens of focal length 2.92 cm (4)Concave lens of focal length 17.5 cm", "options": [{"key": "A", "text": "(3) only"}, {"key": "B", "text": "(2) and (3) only"}, {"key": "C", "text": "(1) and (4) only"}, {"key": "D", "text": "(1), (2), (3) and (4)"}], "answer": "D", "hint": "Let f be the foal length. If the lens is convex and the object distance is greater than 2f, a diminished image is formed. Since the object distance is not given, (1) and (2) may be used."},
  {"id": "ch35-m05", "section": "magnification-lens-formula", "difficulty": "Applied", "stem": "What is the focal length of the lens?", "options": [{"key": "A", "text": "4 cm"}, {"key": "B", "text": "6 cm"}, {"key": "C", "text": "8 cm"}, {"key": "D", "text": "30 cm"}], "answer": "B", "hint": "What is the focal length of the lens?", "image": {"src": "./assets/ch35-m05-fig.png", "alt": "Diagram for ch35-m05", "caption": "Fig · ch35-m05"}},
  {"id": "ch35-m06", "section": "magnification-lens-formula", "difficulty": "Standard", "stem": "The magnification of an image is 2, and the distance between the image and the lens is 8 cm. Which of the following may be the distance between the image and the object? (1)4 cm (2)8 cm (3)12 cm", "options": [{"key": "A", "text": "(3) only"}, {"key": "B", "text": "(1) and (3) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "B", "hint": "u = = = Since the image is magnified, the lens must be convex. There are two scenarios the image can be formed. Scenario 1: If the object distance is between f and 2f, the image and the object are on opposite sides of the lens. Scenario 2: If the object distance is smaller than f, the image and the object are on the sa"},
  {"id": "ch35-m07", "section": "magnification-lens-formula", "difficulty": "Applied", "stem": "In the figure below, the positions of an object and its image formed by a convex lens are shown. The focal length of the lens is", "options": [{"key": "A", "text": "1 cm, 0.75 cm"}, {"key": "B", "text": "1 cm, 1.5 cm"}, {"key": "C", "text": "9 cm, 2.25 cm"}, {"key": "D", "text": "9 cm, 4.5 cm"}], "answer": "D", "hint": "An object is placed in front of a lens and an erect image is formed from the lens. Which of the following is the correct description of the lens? Focal length Type of the lens diverging lens converging lens diverging lens", "image": {"src": "./assets/ch35-m07-fig.png", "alt": "Diagram for ch35-m07", "caption": "Fig · ch35-m07"}},
  {"id": "ch35-m08", "section": "magnification-lens-formula", "difficulty": "Standard", "stem": "An object is placed 10 cm in front of a lens and an erect image is formed 6 cm from the lens. Which of the following is the correct description of the lens?", "options": [{"key": "A", "text": "3.75 cm, diverging lens"}, {"key": "B", "text": "3.75 cm, converging lens"}, {"key": "C", "text": "15 cm, diverging lens"}, {"key": "D", "text": "15 cm, converging lens"}], "answer": "C", "hint": "Since the image is erect and diminished, the lens is diverging (concave) and the image is virtual. The focal length of the lens is . 9.A student holds a lens above a piece of paper. The image of the letters 'AT' is shown in the figure below. Its magnification is 3. PHYSICS AT WORKlensATPHYSICS AT WORKlensAT"},
  {"id": "ch35-m09", "section": "magnification-lens-formula", "difficulty": "Applied", "stem": "The figure shows a lens used in a Physics at Work experiment. Find the image distance and the focal length of the lens.", "options": [{"key": "A", "text": "1 cm, 0.75 cm"}, {"key": "B", "text": "1 cm, 1.5 cm"}, {"key": "C", "text": "9 cm, 2.25 cm"}, {"key": "D", "text": "9 cm, 4.5 cm"}], "answer": "D", "hint": "Since the image is erect and magnified, the lens is convex. image distance = mu = 3 3 =", "image": {"src": "./assets/ch35-m09-fig.png", "alt": "Diagram for ch35-m09", "caption": "Fig · ch35-m09"}},
  {"id": "ch35-m10", "section": "magnification-lens-formula", "difficulty": "Standard", "stem": "A luminous point object is placed 3 cm above the principal axis of a converging lens of focal length 10 cm. Its image is 5 cm below the axis. How far is the object from the lens?", "options": [{"key": "A", "text": "4 cm"}, {"key": "B", "text": "5.33 cm"}, {"key": "C", "text": "12 cm"}, {"key": "D", "text": "16 cm"}], "answer": "D", "hint": "For this object, The object is from the lens."},
  {"id": "ch36-v01", "section": "concave-lens", "difficulty": "Foundation", "stem": "Which of the following statements about lenses is/are correct? (1)Convex and concave lenses form images by refraction. (2)Convex lenses are thinner in the middle. (3)Concave lenses are diverging lenses.", "options": [{"key": "A", "text": "(1) only"}, {"key": "B", "text": "(1) and (3) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "B", "hint": "Light rays are bent due to refraction when entering and leaving a lens. ∴ (1) is correct. ∴ (2) is incorrect."},
  {"id": "ch36-v02", "section": "concave-lens", "difficulty": "Standard", "stem": "In the figure below, lens L is a concave lens and F' is its principal focus. Which of the rays is wrongly drawn?", "options": [{"key": "A", "text": "P"}, {"key": "B", "text": "Q"}, {"key": "C", "text": "R"}, {"key": "D", "text": "S"}], "answer": "B", "hint": "In the figure below, lens L is a concave lens and F' is its principal focus. Which of the rays is wrongly drawn? LF'PQRS LF'PQRS F' F'", "image": {"src": "./assets/ch36-v02-fig.png", "alt": "Diagram for ch36-v02", "caption": "Fig · ch36-v02"}},
  {"id": "ch36-v03", "section": "concave-lens", "difficulty": "Standard", "stem": "Which of the following correctly describe the nature of an image formed by a concave lens? (1)Erect (2)Magnified (3)Virtual", "options": [{"key": "A", "text": "(1) only"}, {"key": "B", "text": "(3) only"}, {"key": "C", "text": "(1) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "C", "hint": "Which of the following correctly describe the nature of an image formed by a concave lens? (1)Erect (2)Magnified (3)Virtual"},
  {"id": "ch36-v04", "section": "concave-lens", "difficulty": "Standard", "stem": "The image formed by a concave lens must be", "options": [{"key": "A", "text": "real, erect and magnified."}, {"key": "B", "text": "real, erect and diminished."}, {"key": "C", "text": "virtual, inverted and magnified."}, {"key": "D", "text": "virtual, erect and diminished."}], "answer": "D", "hint": "The image formed by a concave lens must be"},
  {"id": "ch36-v05", "section": "concave-lens", "difficulty": "Applied", "stem": "An object is put in front of a lens and a virtual image is formed. The figure below shows the positions of the object and the image. What is the focal length of the lens?", "options": [{"key": "A", "text": "5 cm"}, {"key": "B", "text": "10 cm"}, {"key": "C", "text": "15 cm"}, {"key": "D", "text": "20 cm"}], "answer": "C", "hint": "Only a concave lens can form an erect and diminished image, so both the object and its image are on the same side of the lens.", "image": {"src": "./assets/ch36-v05-fig.png", "alt": "Diagram for ch36-v05", "caption": "Fig · ch36-v05"}},
  {"id": "ch36-v06", "section": "concave-lens", "difficulty": "Standard", "stem": "F and F' are the principal foci of a concave lens. Which of the following ray diagrams is/are incorrect? (1) (2) (3)", "options": [{"key": "A", "text": "(2) only"}, {"key": "B", "text": "(1) and (3) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "D", "hint": "Only incident rays parallel to the will bend after passing through the lens so that they appear to come from the principal focus F'. ∴ (1), (2) and (3) are incorrect. 7. In the following diagram, intervals AB, BC, CD, DE and EF are of equal length. An object is placed at O. When a lens is put in front of the object, an", "image": {"src": "./assets/ch36-v06-fig.png", "alt": "Diagram for ch36-v06", "caption": "Fig · ch36-v06"}},
  {"id": "ch36-v07", "section": "concave-lens", "difficulty": "Standard", "stem": "In the following diagram, intervals AB, BC, CD, DE and EF are of equal length. An object is placed at O. When a lens is put in front of the object, an image is formed at I. Which of the following show(s) the possible position(s), type(s) and focal length(s) of the lens? (1)convex lens, about 1 interval (2)concave lens, about 2 intervals (3)convex lens, about 1 interval", "options": [{"key": "A", "text": "(1) only"}, {"key": "B", "text": "(2) only"}, {"key": "C", "text": "(1) and (3) only"}, {"key": "D", "text": "(2) and (3) only"}], "answer": "B", "hint": "about 1 intervals", "image": {"src": "./assets/ch36-v07-fig.png", "alt": "Diagram for ch36-v07", "caption": "Fig · ch36-v07"}},
  {"id": "ch36-v08", "section": "concave-lens", "difficulty": "Foundation", "stem": "Which of the following statements about the image formed by a concave lens is/are correct? (1)It is always between the lens and object. (2)It is always diminished. (3)It will be formed at infinity if the object is located at the focus of the lens.", "options": [{"key": "A", "text": "(1) only"}, {"key": "B", "text": "(3) only"}, {"key": "C", "text": "(1) and (2) only"}, {"key": "D", "text": "(2) and (3) only"}], "answer": "C", "hint": "Which of the following statements about the image formed by a concave lens is/are correct? (1)It is always between the lens and object. (2)It is always diminished. (3)It will be fo"},
  {"id": "ch36-v09", "section": "concave-lens", "difficulty": "Applied", "stem": "An object is placed in front of a concave lens and an image is formed. The positions of the image and the lens are shown below. The focal length of the concave lens is 9 cm. The object distance is", "options": [{"key": "A", "text": "6 cm"}, {"key": "B", "text": "12 cm"}, {"key": "C", "text": "18 cm"}, {"key": "D", "text": "24 cm"}], "answer": "C", "hint": "The image formed by a concave lens is virtual. Therefore, v = .", "image": {"src": "./assets/ch36-v09-fig.png", "alt": "Diagram for ch36-v09", "caption": "Fig · ch36-v09"}},
  {"id": "ch36-v10", "section": "concave-lens", "difficulty": "Applied", "stem": "In the following diagram, lenses X and Y are made of the same material but have different shapes, while lenses X and Z are made of different materials but have the same shape. Which of the following statements is/are correct? (1)X, Y and Z are diverging lenses. (2)Y has a shorter focal length than X. (3)Z has a shorter focal length than X.", "options": [{"key": "A", "text": "(2) only"}, {"key": "B", "text": "(3) only"}, {"key": "C", "text": "(2) and (3) only"}, {"key": "D", "text": "(1), (2) and (3)"}], "answer": "D", "hint": "Which of the following statements is/are correct? (1)X, Y and Z are diverging lenses. (2)Y has a shorter focal length than X. (3)Z has a shorter focal length than X.", "image": {"src": "./assets/ch36-v10-fig.png", "alt": "Diagram for ch36-v10", "caption": "Fig · ch36-v10"}},
];
